version: "3"
services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    ports:
      - ${MONGODB_PORT}:27017
    volumes:
      - data:/data/db
    networks:
      - shipit
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${BOT_PORT}:3000
      - ${EXPRESS_PORT}:3001
    networks:
      - shipit
  proxy:
    build:
      context: ./proxy
      dockerfile: ./Dockerfile
    ports:
      - 3000:80
    networks:
      - shipit

volumes: 
  data:
networks:
  shipit:
    driver: bridge