version: "3"
services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    ports:
      - ${MONGODB_PORT}:27017
    volumes:
      - data:/var/lib/mongodb-bot/data
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
      - 3001:3001
    network_mode: host

volumes: 
  data: