version: v1.0
name: AWS-Deploy
agent:
  machine:
    type: e1-standard-2
  containers:
    - name: main
      image: '171305397109.dkr.ecr.us-east-1.amazonaws.com/docker-images-python-semaphore-deployment:latest'
  image_pull_secrets:
    - name: aws-ecr
blocks:
  - name: Deploy to AWS using ECS
    task:
      secrets:
        - name: AWS
        - name: shipit-service
      jobs:
        - name: Deployment
          commands:
            - checkout
            - python3 ~/semaphore_deploy.py